In [1]:
import pandas as pd

In [2]:
def proccess(data):
    if data["tranaction_type"] == "Sell":
        data["pnl"] = ((data["entry"] - data["exit"])/data["entry"])*100
    else:
        data["pnl"] = ((-data["entry"] + data["exit"])/data["entry"])*100
    return data

In [10]:
def run():
    dict_data = {"script":[],"date":[],"pnl":[]}
    for sy in ["BAJFINANCE"]:
        for year in range(2019,2025):
            df = pd.read_csv(f"backtest/9_ema/{year}-{sy}.csv")
            # df = df[df['date']<df['exit_time']]
            df = df.apply(proccess,axis=1)
            df2=df.dropna(axis=0)
            print(year)
            sum = df2["pnl"].sum(axis=0)
            dict_data["date"].append(year)
            dict_data["script"].append(sy)
            dict_data["pnl"].append((sum/df2["entry"].iloc[0])*100)
    return pd.DataFrame(dict_data)

In [11]:
df = run()
# df.sort_values(by='pnl',ascending=False)
df

2019
2020
2021
2022
2023
2024

  script  date       pnl
0   LTIM  2019 -0.394395
1   LTIM  2020 -0.364033
2   LTIM  2021 -0.323307
3   LTIM  2022 -0.489491
4   LTIM  2023 -0.350718
5   LTIM  2024 -0.415738

In [36]:
df = pd.read_csv(f"strategy_list/2024-BAJFINANCE.csv")
df = df.apply(proccess,axis=1)
df.drop(columns=["Unnamed: 0"], axis=1)
df["date"] = df["entry_time"].apply(lambda x : x.split(" ")[0])
df["month"] = df["date"].apply(lambda x : x.split("-")[1])
df.groupby(["month"])["pnl"].sum()

month
01   -0.943720
02   -2.811495
03   -6.687285
Name: pnl, dtype: float64

In [37]:
df = pd.read_csv(f"strategy_list/2024-BAJFINANCE.csv")
df = df.apply(proccess,axis=1)
df.drop(columns=["Unnamed: 0"], axis=1)
df["date"] = df["entry_time"].apply(lambda x : x.split(" ")[0])
df["month"] = df["date"].apply(lambda x : x.split("-")[1])
df.groupby(["month"])["pnl"].sum()

month
04    3.107526
05    7.357994
06   -1.533511
07   -0.593059
Name: pnl, dtype: float64

In [3]:
def performance():
    data = {
        "month":[],
        "year":[],
        "pnl":[],
    }
    df_year = None
    for year in range(2024,2025):
        for month in range(1,13):
            try:
                df = pd.read_csv(f"strategy_list/9_ema/INDUSINDBK-5-{month}-{year}.csv")
                df.drop(columns=["Unnamed: 0"], axis=1)
                df["date"] = df["entry_time"].apply(lambda x : x.split(" ")[0])
                df["month"] = df["date"].apply(lambda x : x.split("-")[1])
                df["day"] = df["date"].apply(lambda x : x.split("-")[2])
                # new_df = df[df["day"]=="01"]
                data["month"].append(month)
                data["year"].append(year)
                data["pnl"].append(df.groupby(["month"])["pnl"].sum().values[0])
            except Exception as e:
                print(e)
    df = pd.DataFrame(data)
    df.set_index("year", inplace=True)
    return df

#

In [4]:
df = performance()

'entry_time'
'entry_time'
'entry_time'
'entry_time'

In [5]:

df.sort_values("pnl", ascending=False)

      month    pnl
year
2024      6  31.48
2024      7  27.63
2024      4  26.67
2024      3  25.23
2024      5  24.74
2024      2  21.53
2024      1  19.67
2024      8   8.36

    month  year     pnl
46     11  2023    8.41
55      8  2024    8.64
45     10  2023   11.75
39      4  2023   11.81
41      6  2023   13.27
34     11  2022   15.13
43      8  2023   15.52
44      9  2023   15.86
50      3  2024   16.78
40      5  2023   17.53
27      4  2022   17.81
30      7  2022   18.57
47     12  2023   18.88
18      7  2021   19.07
33     10  2022   19.47
48      1  2024   19.59
29      6  2022   19.76
31      8  2022   19.81
51      4  2024   20.18
9      10  2020   20.49
35     12  2022   20.55
20      9  2021   21.49
37      2  2023   21.50
0       1  2020   21.75
54      7  2024   21.79
17      6  2021   24.28
36      1  2023   24.41
42      7  2023   24.55
23     12  2021   25.21
7       8  2020   26.01
19      8  2021   26.08
38      3  2023   26.90
32      9  2022   26.98
52      5  2024   27.31
24      1  2022   27.68
8       9  2020   28.02
16      5  2021   29.42
22     11  2021   30.05
21     10  2021   30.79
6       7  2020   31.28
11     12  2020   32.43
15      4  2021   32.49
53      6  2024   33.32
25      2  2022   33.49
1       2  2020   33.90
26      3  2022   34.02
49      2  2024   34.45
13      2  2021   34.80
3       4  2020   36.43
4       5  2020   36.62
28      5  2022   37.57
10     11  2020   38.12
5       6  2020   38.51
12      1  2021   38.52
14      3  2021   38.81
2       3  2020  110.68